### ISSUE TITLE
preparation steps for inference

### ISSUE THREAD

**Issue by simaker** [ZwwWayne/mmMOT#8]
Hi ZwwWayne,
which steps are necessary to create the fitting data structure in pp_val_dets.pkl? You said, you have used the SECOND Detector for detection. But the data structure and the results in the .pkl file have a different shape than in mmMot and pp_train_dets.pkl. 
Which additional steps are necessary to import a detection result from SECOND and use it for mmMOT, if you are not using the pkl files from google drive?

Thank you :)

**Comment by ZwwWayne** [comment]
1. This might because of the version problem. During the paper submission process, we are using v1.0 SECOND rather than v1.5 but it should be easy to change the key.
2. The data structure is a little bit different since tracking data is using the sequence but detection data is not organized in this way. At that time we use this [data_converter](https://github.com/umautobots/vod-converter) to convert the tracking data to the detection data format for inference. But from today's perspective, this step is actually not necessary. In the future, we may skip this step and provide an easier manner.

**Comment by simaker** [comment]
1) but how can i use create_data.py of SECOND? The script requires only integers as image_idx and not xxxx-xxxxxx.
2) The version solved the problem. Firstly I used v1.6. with 1.5 ist is working

**Comment by ZwwWayne** [comment]
You can either build a mapping list or change the SECOND's code to accept the string index.

**Comment by simaker** [comment]
okay i've done that. Now it is working. Thanks for your support
